### ISSUE TITLE
Improve README

### ISSUE THREAD

**Issue by patcon** [cadecairos/matterbridge-heroku#2]
Like so: https://github.com/patcon/matterbridge-heroku#readme

Will submit PR

**Comment by patcon** [comment]
Ohai! Just realized you were in Newmarket, Ontario and working with Mozilla...! Is Mozilla using Matterbridge? Really curious about any details that you can share :)

**Comment by patcon** [comment]
bump

**Comment by cadecairos** [comment]
> Ohai! Just realized you were in Newmarket, Ontario and working with Mozilla...! Is Mozilla using Matterbridge? Really curious about any details that you can share :)

We used to Mattermost+Matterbridge, but decisions were made somewhere above me to use Slack instead. :(

Feel free to submit that PR and we'll work to get it merged

**Comment by patcon** [comment]
Going to close this in favour of #5 🎉
