### ISSUE TITLE
Consider bringing on a co-maintainer

### ISSUE THREAD

**Issue by patcon** [cadecairos/matterbridge-heroku#4]
Hi @cadecairos! I feel like you might be a bit busy with other projects. I totally understand that :)

Any chance I could help tidy up and manage the issue queue? I'd be happy to agree that we only merge with +1's, or some other protocol.

Push access would let me merge PRs

Thanks!

**Comment by cadecairos** [comment]
Hi @patcon I'd be glad to bring you on as a co-maintainer. We used to use Mattermost at my work but a decision was made above my head that brought in Slack instead, so this project kind of fell into limbo.

I've invited you on as a collaborator.

**Comment by patcon** [comment]
You da best!

But just to get clarity -- you know that Matterbridge works with Slack now too, right? :)

**Comment by cadecairos** [comment]
It doesn't surprise me that it works with slack, But I doubt I could get our legal and security folks to approve an itegration with another messaging application XD

**Comment by patcon** [comment]
Heh rats. Well anyhow, I'm working on an autoconfiguration app over here, in case it's ever useful to you: https://github.com/patcon/matterbridge-autoconfig

It currently works for creating language-translation rooms in the same slack, but it could easily be extended for something like "auto-creating public gitter rooms" based on naming conventions. I could imagine that maybe being in the spirit of some mozilla work :)

**Comment by cadecairos** [comment]
wow, that's really cool! I didn't even know Matterbridge did automatic translation
